### ISSUE TITLE
Return pipeline stage results when calling buildStages()

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#165]
`buildStages()` method shall be able to gather and return the outputs of each stage being created.

Likewise, JePL should provide a means to access those outputs once the build has been completed (SQAaaS API is the obvious use case). A possible solution to this issue is to generate a JSON file and store it as part of the Jenkins build metadata.

Depends on https://github.com/indigo-dc/jenkins-pipeline-library/issues/162

**Comment by samuelbernardolip** [comment]
@orviz I think this issue is outdated, since current implementation don't need this.
Also JePL is not intended to return any output. Any information about the pipelines should be collected from Jenkins API, or using any reporting plugin or any script managed by the pipeline definition.
I'm closing this issue for now.
