### ISSUE TITLE
Turn ConfigParser map keys to groovy variable name convention

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#31]
Example: `stageMap.tox.tox_file` to `stageMap.tox.toxFile`

**Comment by samuelbernardolip** [comment]
I do that because I was not sure if the parser was defining the Map keys with the original labels.
I'm not sure if groovy code style applies to Map keys...
As I could understand, camel case convention are for language first citizens. The keys are internal to data representation.
Also syntax checker and code linting don't comply about that.
Is config parser building the map using camel case to keys identifiers?

**Comment by orviz** [comment]
We agree on accessing the Map keys with brackets instead of dots. Need to review the code to ensure it is compliant with this convention.

**Comment by orviz** [comment]
After discussing this, we are not adopting an unique convention for this. Dot notation is handy for some cases.
